### ISSUE TITLE
Backend Integration Of Gallery

### ISSUE THREAD

**Issue by realswikarrr** [Sajani55/Content-Management-System#10]

**Comment by Sajani55** [comment]
@realswikarrr can you please provide the description about it?

**Comment by realswikarrr** [comment]
@Sajani55 The issue was about integrating the backend with the gallery means we need to get the pictures from the backend side to the frontend

![image](https://user-images.githubusercontent.com/80502023/118375053-f2743000-b5de-11eb-82a5-e1b569b3b696.png)

And also this images should be fetched through the backend side

This is completed successfully
