### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Sajani55** [Sajani55/Content-Management-System#14]
As a user 
I want to see the map
so that i can find the location of college

**Comment by Sajani55** [comment]
This is already done by our frontend devloper.

**Comment by thebuggybug** [comment]
the maps section is done usiing iframe and google map embedded link. The map feature iis present in contact page. 
![image (12)](https://user-images.githubusercontent.com/68284654/117969494-32b98100-b347-11eb-8026-5754e6229eb6.png)

**Comment by Sajani55** [comment]
Does this map have zoom in and zoom out feature? @thebuggybug

**Comment by thebuggybug** [comment]
Yes it has the feature for zoom
For desktop interface hold cltr and use mouse scroll wheel
For mobile ui we can use pinch gesture

**Comment by Sajani55** [comment]
Ok then. Seems Good to me.
