### ISSUE TITLE
Cannot click the view more button

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#19]
![image](https://user-images.githubusercontent.com/71198536/118342978-bc36a200-b545-11eb-9d1e-aebff9321152.png)

Steps to reproduce:

1.  Go to home page
2. click to courses
3. click to available courses
4. click to view more
5. The view more button is not working .

Environment: window 10 brave Version 1.24.85 Chromium: 90.0.4430.212

**Comment by thebuggybug** [comment]
this issue has been fixed in recent updates. Now the button functions . Team mates can see changes by pulling recent version of application through git.
