### ISSUE TITLE
Error message not displaying while submitting Contact form using wrong email syntax.

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#20]
![image](https://user-images.githubusercontent.com/71198536/118346936-0aa46a80-b55f-11eb-98a4-eef374ef221c.png)

**Steps to reproduce:**

1. Go to Website of herald Cms
2. click to contact page
3. Enter full name
4. Enter email
5. Enter subject
6. Enter your message
7. Click send
8.  Error message not being displayed.

**Environment**: window 10 brave Version 1.24.85 Chromium: 90.0.4430.212

**Comment by thebuggybug** [comment]
this issue will be fixed by backend dev. as the input forms data need to be processed to backend.

**Comment by realswikarrr** [comment]
![image](https://user-images.githubusercontent.com/80502023/118356296-3b52c700-b594-11eb-87ff-562f650a121f.png)

The error message is showing properly with the error !! 

![image](https://user-images.githubusercontent.com/80502023/118356305-4d346a00-b594-11eb-9ca7-bf7b4f5ea4e0.png)

Here is the code for this issue , just needed to add the types and names to it which is successfully added to it

**Comment by Sujal465** [comment]
before the contact form was not validate, the issue of this contact form now has been validate and updated. now its showing the error message.
![Screenshot (106)](https://user-images.githubusercontent.com/80870270/118386992-3a28a500-b63b-11eb-8c19-db0e2f866b15.png)

**Comment by Sujal465** [comment]
updated code
![Screenshot (107)](https://user-images.githubusercontent.com/80870270/118387021-6c3a0700-b63b-11eb-8a9a-9111bfe0c9dc.png)

**Comment by Sujal465** [comment]
![Screenshot (108)](https://user-images.githubusercontent.com/80870270/118387031-778d3280-b63b-11eb-8606-77fb5b3999fb.png)
