### ISSUE TITLE
The browse more button is not working.

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#21]
![image](https://user-images.githubusercontent.com/71198536/118348388-a3d87e80-b569-11eb-8d89-2be220601b48.png)

**Steps to reproduce:**

1. Go to Website of herald Cms
2. click to Event page
3. Click browse all event button
4. The button is not working.

**Environment:** window 10 brave Version 1.24.85 Chromium: 90.0.4430.212

**Comment by thebuggybug** [comment]
This issue will be fixed once the backend server  starts in local server (strapi)
This is occurring because its lacking local backend servdr
