### ISSUE TITLE
Content has been dismanaged in the contact us page 

### ISSUE THREAD

**Issue by realswikarrr** [Sajani55/Content-Management-System#22]
![image](https://user-images.githubusercontent.com/80502023/118356368-b320f180-b594-11eb-93cd-73c0dfb02408.png)

The content is not managed after the backend code hopefully you will fix it

**Comment by thebuggybug** [comment]
hello ! this issue has been solved .
just we need to add `<MDBRow>` before `<MDBCol>` to wrap entire column contents inside row to fix the issue.
![image](https://user-images.githubusercontent.com/68284654/118358402-51658500-b59e-11eb-89b5-c53e95c89f26.png)
![image](https://user-images.githubusercontent.com/68284654/118358414-5b878380-b59e-11eb-8d0d-9b2d75df35e2.png)
