### ISSUE TITLE
Unsuitable title for contact details

### ISSUE THREAD

**Issue by thebuggybug** [Sajani55/Content-Management-System#23]
please add appropriate name to the titles:
like
First --> Institution anem
seconf --> Address 
third --> contact 
fourth -->
 email![image.png](https://user-images.githubusercontent.com/68284654/118367764-d792c300-b5c0-11eb-9642-a8303629013b.png)

**Comment by realswikarrr** [comment]
![image](https://user-images.githubusercontent.com/80502023/118374314-1cc3ee80-b5db-11eb-8504-f93109a7eb2f.png)

These bug has been fixed as i have fixed the title of the contacts in detailed way.

You can visit the strapi repo and pull the changes according to it.
