### ISSUE TITLE
Inappropriate tittle in form(backend) 

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#24]
![image](https://user-images.githubusercontent.com/71198536/118384612-22472600-b627-11eb-9ab0-937d06cfb270.png)

**Steps to reproduce:**

1. Login to strapi as admin
2. Go to map content
3. Title for detail is not appropriate.

**Environment: window** 10 brave Version 1.24.85 Chromium: 90.0.4430.212

**Comment by realswikarrr** [comment]
Why open it again ? this issue have been already fixed and closed with my comments

![Uploading image.png…]()
