### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#3]
As a user, 
I want to see all the photos taken by college,
so that I can review them

**Comment by realswikarrr** [comment]
Done !!

**Comment by realswikarrr** [comment]
Done

**Comment by thebuggybug** [comment]
the image gallery has been desiigned and developed with react lightbox UI library. This library helps to wrap all images in one main <div> and the images can be viewed as slideshow or gallery when clicked. 
![image (6)](https://user-images.githubusercontent.com/68284654/117969186-d3f40780-b346-11eb-87b1-f0a1aec5ed88.png)

**Comment by Sajani55** [comment]
@thebuggybug it would be good if the image was little big.

**Comment by thebuggybug** [comment]
The image will in full screen once good quality high resolution image is provided. since this is purely hard coded i have used small res.image to render fast. The final version will view full screen image
