### ISSUE TITLE
Courses 

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#4]
As a user,
I want to see different kind of courses offered by college,
so that I can review what should I learn.

**Comment by Sajani55** [comment]
This is an issue created for sprint 2. All the frontend developers will work on this. Here they will add the courses available in Herald College

**Comment by thebuggybug** [comment]
the course section has been designed and coded. It gives short description about courses and available courses. With a button which takes user to single course page where all the description about the course is viewed.

**Comment by Sajani55** [comment]
Completed

**Comment by Sajani55** [comment]
@thebuggybug can you please say me what do you mean by the description about the code is viewed . Do you mean it will show all the modules of the selected course page?

**Comment by thebuggybug** [comment]
The description is referred as FaQ for course

**Comment by realswikarrr** [comment]
![image](https://user-images.githubusercontent.com/80502023/118375170-ae355f80-b5df-11eb-9f5c-e391784d6c45.png)

The single course and course are also integrated through the backend successfully, we will get the content through the backend now.

![image](https://user-images.githubusercontent.com/80502023/118375189-cb6a2e00-b5df-11eb-88fe-aaa3b424100e.png)

![image](https://user-images.githubusercontent.com/80502023/118375192-d0c77880-b5df-11eb-8e14-891e9f5880ed.png)
