### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#5]
As a user,
I want to contact college,
so that it will be easier for me.

**Comment by Sajani55** [comment]
This is an incomplete issue. Sujal  Ghimire is working on this isssue.

**Comment by Sujal465** [comment]
I completed contact form and here is the proof
![Screenshot (85)](https://user-images.githubusercontent.com/80870270/115004953-156bd100-9ec7-11eb-8fd3-c90c0c454971.png)

**Comment by Sajani55** [comment]
@Sujal465 it would be nice if you could add  one image  in Contact section.

**Comment by Sujal465** [comment]
before the design of the contact form was another and now it has been changed to this
@bshamir 
![Screenshot (92)](https://user-images.githubusercontent.com/80870270/118354518-21f94d00-b58b-11eb-90f5-2186d6cfbd10.png)
@Sajani55

**Comment by Sujal465** [comment]
contact details have been changed
![Screenshot (94)](https://user-images.githubusercontent.com/80870270/118354564-5a992680-b58b-11eb-8a96-8af77c1ad6cb.png)

**Comment by bshamir** [comment]
It seems good @Sujal465 .
