### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#7]
As a user,
 I want to view  user testimonials,
so that i can review and get feedbacks.

**Comment by Sajani55** [comment]
This has not been completed yet. We will complete this user story in sprint 2.

**Comment by realswikarrr** [comment]
Done

**Comment by thebuggybug** [comment]
the frontend ssection for testimonial is designed where it displays testimonial given by user. This has two major components which are user testimonial quote and aurthor. Testimonial lies in application's Homepage
![image (3)](https://user-images.githubusercontent.com/68284654/117967783-30562780-b345-11eb-8805-93d116df9849.png)

**Comment by Sajani55** [comment]
![](https://user-images.githubusercontent.com/68284654/117967783-30562780-b345-11eb-8805-93d116df9849.png)

 It would be nice to have inverted comma in testimonial. It woud look more good. @thebuggybug #7

**Comment by thebuggybug** [comment]
yeah sure !! the following frontend requirement has been fulfilled. 
here is the attached Screenshot showing output.
 Now there will be inverted Comma and the first letter wll be larger and different in color than entire text. I have attched image of debug. Added this to CSS `.testimonial-text::first-letter{
  font-size: 250%;
  color: #74C042;
}`
![image](https://user-images.githubusercontent.com/68284654/118264553-9672b400-b4d7-11eb-9f3c-411f59d4ebfa.png)

**Comment by realswikarrr** [comment]
![image](https://user-images.githubusercontent.com/80502023/118375084-2c453680-b5df-11eb-91ae-94a53ea1f087.png)
 
The testimonials are fetched from the backend side as we enter the name and the testimonials it will be fetched through the backend to the frontend

![image](https://user-images.githubusercontent.com/80502023/118375101-4bdc5f00-b5df-11eb-8a73-bd825e73c811.png)
