### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by bshamir** [Sajani55/Content-Management-System#8]
As a user, 
I want to see upcoming events, 
so that i would be able to get some information about it

**Comment by thebuggybug** [comment]
the events section has been created  with cards. There are 4 layers. the top layer where image is viewed, the middle layer has event title, below that short description of event is provided and when user want to read more about event, user should click on **read more** button to view all event detail in dedicated single event page.
![image (7)](https://user-images.githubusercontent.com/68284654/117967431-bf167480-b344-11eb-8617-1c9f499abc15.png)
![image (8)](https://user-images.githubusercontent.com/68284654/117967547-e66d4180-b344-11eb-83cc-a051b16cc3ed.png)
![image (9)](https://user-images.githubusercontent.com/68284654/117967555-e79e6e80-b344-11eb-8415-d5ec9a40cc36.png)
![image (10)](https://user-images.githubusercontent.com/68284654/117967556-e8370500-b344-11eb-86ec-b77a30a93359.png)

**Comment by realswikarrr** [comment]
The event section content have been fetched through backend successfully 

![image](https://user-images.githubusercontent.com/80502023/118375139-79c1a380-b5df-11eb-88b1-b0c86def6304.png)

![image](https://user-images.githubusercontent.com/80502023/118375144-82b27500-b5df-11eb-8ce1-f6e5a5a3e9ee.png)

As we upload events on the backend side the events will be deployed and showed on the frontend part
